diff --git a/render.yaml b/render.yaml
new file mode 100644
index 0000000000000000000000000000000000000000..785e71f67b28fcca86c3ca13451f8be4cd0f1904
--- /dev/null
+++ b/render.yaml
@@ -0,0 +1,62 @@
+services:
+  - type: web
+    name: supermemorynn
+    runtime: docker
+    dockerfilePath: ./Dockerfile
+    plan: free
+    envVars:
+      - key: TG_BOT_TOKEN
+        sync: false
+      - key: TG_CHAT_ID
+        sync: false
+      - key: TG_ADMIN_ID
+        sync: false
+
+      - key: MONITOR_INTERVAL
+        value: "120"
+      - key: MIN_BACKUP_INTERVAL_SEC
+        value: "300"
+      - key: FORCE_BACKUP_EVERY_SEC
+        value: "1800"
+      - key: BACKUP_BINARYDATA
+        value: "false"
+      - key: CHUNK_SIZE
+        value: "19M"
+      - key: LOCAL_HISTORY_KEEP
+        value: "5"
+
+      - key: EXECUTIONS_DATA_PRUNE
+        value: "true"
+      - key: EXECUTIONS_DATA_MAX_AGE
+        value: "24"
+      - key: EXECUTIONS_DATA_SAVE_ON_SUCCESS
+        value: "none"
+      - key: EXECUTIONS_DATA_SAVE_ON_ERROR
+        value: "all"
+      - key: EXECUTIONS_DATA_SAVE_ON_PROGRESS
+        value: "false"
+      - key: EXECUTIONS_MODE
+        value: "regular"
+
+      - key: N8N_PORT
+        value: "5678"
+      - key: PORT
+        value: "5678"
+      - key: N8N_PROTOCOL
+        value: "https"
+      - key: N8N_HOST
+        sync: false
+      - key: WEBHOOK_URL
+        sync: false
+      - key: N8N_ENCRYPTION_KEY
+        sync: false
+      - key: N8N_BASIC_AUTH_ACTIVE
+        value: "true"
+      - key: N8N_BASIC_AUTH_USER
+        sync: false
+      - key: N8N_BASIC_AUTH_PASSWORD
+        sync: false
+      - key: GENERIC_TIMEZONE
+        value: "Asia/Baghdad"
+      - key: N8N_DIAGNOSTICS_ENABLED
+        value: "false"
